import axios from "axios";

interface VideoData {
    id: number,
    hostName: string,
    hostAvatar: string,
    hostId: number,
    hosttoken: string,
    title: string,
    content: string,
    videoUrl: string,
    coverUrl: string,
    loveCount: number,
    fensiCount: number,
    timer: string,
    longer: string,
    alt: string,
    commentCount: number,
}

// 视频数据映射，按 tabcar 分类
const videoDataMap: Record<number, VideoData[]> = {
    1: [
        {
            id: 1,
            hostName: '主播1',
            hostAvatar: 'https://example.com/avatar1.jpg',
            hostId: 1,
            hosttoken: 'token1',
            title: '视频标题1',
            content: "1235454524",
            videoUrl: 'https://example.com/video1.mp4',
            coverUrl: 'https://example.com/cover1.jpg',
            loveCount: 100,
            fensiCount: 50,
            timer: '2024-06-01 12:00:00',
            longer: '10:00',
            alt: '视频封面1',
            commentCount: 10,
        },
        {
            id: 2,
            hostName: '主播2',
            hostAvatar: 'https://example.com/avatar2.jpg',
            hostId: 2,
            hosttoken: 'token2',
            title: '视频标题2',
            content: "精彩视频内容",
            videoUrl: 'https://example.com/video2.mp4',
            coverUrl: 'https://example.com/cover2.jpg',
            loveCount: 200,
            fensiCount: 100,
            timer: '2024-06-02 12:00:00',
            longer: '08:00',
            alt: '视频封面2',
            commentCount: 20,
        }
    ],
    2: [
        {
            id: 3,
            hostName: '公开课主播1',
            hostAvatar: 'https://example.com/avatar3.jpg',
            hostId: 3,
            hosttoken: 'token3',
            title: '公开课视频1',
            content: "公开课内容",
            videoUrl: 'https://example.com/video3.mp4',
            coverUrl: 'https://example.com/cover3.jpg',
            loveCount: 300,
            fensiCount: 150,
            timer: '2024-06-03 12:00:00',
            longer: '15:00',
            alt: '公开课封面1',
            commentCount: 30,
        },
        {
            id: 4,
            hostName: '公开课主播2',
            hostAvatar: 'https://example.com/avatar4.jpg',
            hostId: 4,
            hosttoken: 'token4',
            title: '公开课视频2',
            content: "公开课内容2",
            videoUrl: 'https://example.com/video4.mp4',
            coverUrl: 'https://example.com/cover4.jpg',
            loveCount: 400,
            fensiCount: 200,
            timer: '2024-06-04 12:00:00',
            longer: '12:00',
            alt: '公开课封面2',
            commentCount: 40,
        }
    ],
    3: [
        {
            id: 5,
            hostName: '游戏主播1',
            hostAvatar: 'https://example.com/avatar5.jpg',
            hostId: 5,
            hosttoken: 'token5',
            title: '游戏视频1',
            content: "游戏精彩时刻",
            videoUrl: 'https://example.com/video5.mp4',
            coverUrl: 'https://example.com/cover5.jpg',
            loveCount: 500,
            fensiCount: 250,
            timer: '2024-06-05 12:00:00',
            longer: '20:00',
            alt: '游戏封面1',
            commentCount: 50,
        },
        {
            id: 6,
            hostName: '游戏主播2',
            hostAvatar: 'https://example.com/avatar6.jpg',
            hostId: 6,
            hosttoken: 'token6',
            title: '游戏视频2',
            content: "游戏攻略",
            videoUrl: 'https://example.com/video6.mp4',
            coverUrl: 'https://example.com/cover6.jpg',
            loveCount: 600,
            fensiCount: 300,
            timer: '2024-06-06 12:00:00',
            longer: '18:00',
            alt: '游戏封面2',
            commentCount: 60,
        }
    ],
    4: [
        {
            id: 7,
            hostName: '二次元主播1',
            hostAvatar: 'https://example.com/avatar7.jpg',
            hostId: 7,
            hosttoken: 'token7',
            title: '二次元视频1',
            content: "动漫推荐",
            videoUrl: 'https://example.com/video7.mp4',
            coverUrl: 'https://example.com/cover7.jpg',
            loveCount: 700,
            fensiCount: 350,
            timer: '2024-06-07 12:00:00',
            longer: '10:00',
            alt: '二次元封面1',
            commentCount: 70,
        },
        {
            id: 8,
            hostName: '二次元主播2',
            hostAvatar: 'https://example.com/avatar8.jpg',
            hostId: 8,
            hosttoken: 'token8',
            title: '二次元视频2',
            content: "动漫解说",
            videoUrl: 'https://example.com/video8.mp4',
            coverUrl: 'https://example.com/cover8.jpg',
            loveCount: 800,
            fensiCount: 400,
            timer: '2024-06-08 12:00:00',
            longer: '12:00',
            alt: '二次元封面2',
            commentCount: 80,
        }
    ],
    5: [
        {
            id: 9,
            hostName: '音乐主播1',
            hostAvatar: 'https://example.com/avatar9.jpg',
            hostId: 9,
            hosttoken: 'token9',
            title: '音乐视频1',
            content: "热门歌曲",
            videoUrl: 'https://example.com/video9.mp4',
            coverUrl: 'https://example.com/cover9.jpg',
            loveCount: 900,
            fensiCount: 450,
            timer: '2024-06-09 12:00:00',
            longer: '04:00',
            alt: '音乐封面1',
            commentCount: 90,
        },
        {
            id: 10,
            hostName: '音乐主播2',
            hostAvatar: 'https://example.com/avatar10.jpg',
            hostId: 10,
            hosttoken: 'token10',
            title: '音乐视频2',
            content: "翻唱作品",
            videoUrl: 'https://example.com/video10.mp4',
            coverUrl: 'https://example.com/cover10.jpg',
            loveCount: 1000,
            fensiCount: 500,
            timer: '2024-06-10 12:00:00',
            longer: '05:00',
            alt: '音乐封面2',
            commentCount: 100,
        }
    ],
    6: [
        {
            id: 11,
            hostName: '影视主播1',
            hostAvatar: 'https://example.com/avatar11.jpg',
            hostId: 11,
            hosttoken: 'token11',
            title: '影视视频1',
            content: "电影解说",
            videoUrl: 'https://example.com/video11.mp4',
            coverUrl: 'https://example.com/cover11.jpg',
            loveCount: 1100,
            fensiCount: 550,
            timer: '2024-06-11 12:00:00',
            longer: '15:00',
            alt: '影视封面1',
            commentCount: 110,
        },
        {
            id: 12,
            hostName: '影视主播2',
            hostAvatar: 'https://example.com/avatar12.jpg',
            hostId: 12,
            hosttoken: 'token12',
            title: '影视视频2',
            content: "电视剧推荐",
            videoUrl: 'https://example.com/video12.mp4',
            coverUrl: 'https://example.com/cover12.jpg',
            loveCount: 1200,
            fensiCount: 600,
            timer: '2024-06-12 12:00:00',
            longer: '20:00',
            alt: '影视封面2',
            commentCount: 120,
        }
    ],
    7: [
        {
            id: 13,
            hostName: '美食主播1',
            hostAvatar: 'https://example.com/avatar13.jpg',
            hostId: 13,
            hosttoken: 'token13',
            title: '美食视频1',
            content: "美食制作",
            videoUrl: 'https://example.com/video13.mp4',
            coverUrl: 'https://example.com/cover13.jpg',
            loveCount: 1300,
            fensiCount: 650,
            timer: '2024-06-13 12:00:00',
            longer: '08:00',
            alt: '美食封面1',
            commentCount: 130,
        },
        {
            id: 14,
            hostName: '美食主播2',
            hostAvatar: 'https://example.com/avatar14.jpg',
            hostId: 14,
            hosttoken: 'token14',
            title: '美食视频2',
            content: "探店视频",
            videoUrl: 'https://example.com/video14.mp4',
            coverUrl: 'https://example.com/cover14.jpg',
            loveCount: 1400,
            fensiCount: 700,
            timer: '2024-06-14 12:00:00',
            longer: '10:00',
            alt: '美食封面2',
            commentCount: 140,
        }
    ],
    8: [
        {
            id: 15,
            hostName: '知识主播1',
            hostAvatar: 'https://example.com/avatar15.jpg',
            hostId: 15,
            hosttoken: 'token15',
            title: '知识视频1',
            content: "科普知识",
            videoUrl: 'https://example.com/video15.mp4',
            coverUrl: 'https://example.com/cover15.jpg',
            loveCount: 1500,
            fensiCount: 750,
            timer: '2024-06-15 12:00:00',
            longer: '12:00',
            alt: '知识封面1',
            commentCount: 150,
        },
        {
            id: 16,
            hostName: '知识主播2',
            hostAvatar: 'https://example.com/avatar16.jpg',
            hostId: 16,
            hosttoken: 'token16',
            title: '知识视频2',
            content: "历史故事",
            videoUrl: 'https://example.com/video16.mp4',
            coverUrl: 'https://example.com/cover16.jpg',
            loveCount: 1600,
            fensiCount: 800,
            timer: '2024-06-16 12:00:00',
            longer: '15:00',
            alt: '知识封面2',
            commentCount: 160,
        }
    ],
    9: [
        {
            id: 17,
            hostName: '小剧场主播1',
            hostAvatar: 'https://example.com/avatar17.jpg',
            hostId: 17,
            hosttoken: 'token17',
            title: '小剧场视频1',
            content: "短剧片段",
            videoUrl: 'https://example.com/video17.mp4',
            coverUrl: 'https://example.com/cover17.jpg',
            loveCount: 1700,
            fensiCount: 850,
            timer: '2024-06-17 12:00:00',
            longer: '05:00',
            alt: '小剧场封面1',
            commentCount: 170,
        },
        {
            id: 18,
            hostName: '小剧场主播2',
            hostAvatar: 'https://example.com/avatar18.jpg',
            hostId: 18,
            hosttoken: 'token18',
            title: '小剧场视频2',
            content: "搞笑短剧",
            videoUrl: 'https://example.com/video18.mp4',
            coverUrl: 'https://example.com/cover18.jpg',
            loveCount: 1800,
            fensiCount: 900,
            timer: '2024-06-18 12:00:00',
            longer: '08:00',
            alt: '小剧场封面2',
            commentCount: 180,
        }
    ],
    10: [
        {
            id: 19,
            hostName: '生活主播1',
            hostAvatar: 'https://example.com/avatar19.jpg',
            hostId: 19,
            hosttoken: 'token19',
            title: '生活视频1',
            content: "日常vlog",
            videoUrl: 'https://example.com/video19.mp4',
            coverUrl: 'https://example.com/cover19.jpg',
            loveCount: 1900,
            fensiCount: 950,
            timer: '2024-06-19 12:00:00',
            longer: '10:00',
            alt: '生活封面1',
            commentCount: 190,
        },
        {
            id: 20,
            hostName: '生活主播2',
            hostAvatar: 'https://example.com/avatar20.jpg',
            hostId: 20,
            hosttoken: 'token20',
            title: '生活视频2',
            content: "旅行日记",
            videoUrl: 'https://example.com/video20.mp4',
            coverUrl: 'https://example.com/cover20.jpg',
            loveCount: 2000,
            fensiCount: 1000,
            timer: '2024-06-20 12:00:00',
            longer: '12:00',
            alt: '生活封面2',
            commentCount: 200,
        }
    ],
    11: [
        {
            id: 21,
            hostName: '体育主播1',
            hostAvatar: 'https://example.com/avatar21.jpg',
            hostId: 21,
            hosttoken: 'token21',
            title: '体育视频1',
            content: "比赛集锦",
            videoUrl: 'https://example.com/video21.mp4',
            coverUrl: 'https://example.com/cover21.jpg',
            loveCount: 2100,
            fensiCount: 1050,
            timer: '2024-06-21 12:00:00',
            longer: '15:00',
            alt: '体育封面1',
            commentCount: 210,
        },
        {
            id: 22,
            hostName: '体育主播2',
            hostAvatar: 'https://example.com/avatar22.jpg',
            hostId: 22,
            hosttoken: 'token22',
            title: '体育视频2',
            content: "运动教程",
            videoUrl: 'https://example.com/video22.mp4',
            coverUrl: 'https://example.com/cover22.jpg',
            loveCount: 2200,
            fensiCount: 1100,
            timer: '2024-06-22 12:00:00',
            longer: '18:00',
            alt: '体育封面2',
            commentCount: 220,
        }
    ],
    12: [
        {
            id: 23,
            hostName: '旅行主播1',
            hostAvatar: 'https://example.com/avatar23.jpg',
            hostId: 23,
            hosttoken: 'token23',
            title: '旅行视频1',
            content: "风景分享",
            videoUrl: 'https://example.com/video23.mp4',
            coverUrl: 'https://example.com/cover23.jpg',
            loveCount: 2300,
            fensiCount: 1150,
            timer: '2024-06-23 12:00:00',
            longer: '10:00',
            alt: '旅行封面1',
            commentCount: 230,
        },
        {
            id: 24,
            hostName: '旅行主播2',
            hostAvatar: 'https://example.com/avatar24.jpg',
            hostId: 24,
            hosttoken: 'token24',
            title: '旅行视频2',
            content: "旅游攻略",
            videoUrl: 'https://example.com/video24.mp4',
            coverUrl: 'https://example.com/cover24.jpg',
            loveCount: 2400,
            fensiCount: 1200,
            timer: '2024-06-24 12:00:00',
            longer: '12:00',
            alt: '旅行封面2',
            commentCount: 240,
        }
    ],
    13: [
        {
            id: 25,
            hostName: '亲子主播1',
            hostAvatar: 'https://example.com/avatar25.jpg',
            hostId: 25,
            hosttoken: 'token25',
            title: '亲子视频1',
            content: "育儿经验",
            videoUrl: 'https://example.com/video25.mp4',
            coverUrl: 'https://example.com/cover25.jpg',
            loveCount: 2500,
            fensiCount: 1250,
            timer: '2024-06-25 12:00:00',
            longer: '08:00',
            alt: '亲子封面1',
            commentCount: 250,
        },
        {
            id: 26,
            hostName: '亲子主播2',
            hostAvatar: 'https://example.com/avatar26.jpg',
            hostId: 26,
            hosttoken: 'token26',
            title: '亲子视频2',
            content: "宝宝日常",
            videoUrl: 'https://example.com/video26.mp4',
            coverUrl: 'https://example.com/cover26.jpg',
            loveCount: 2600,
            fensiCount: 1300,
            timer: '2024-06-26 12:00:00',
            longer: '10:00',
            alt: '亲子封面2',
            commentCount: 260,
        }
    ],
    14: [
        {
            id: 27,
            hostName: '动物主播1',
            hostAvatar: 'https://example.com/avatar27.jpg',
            hostId: 27,
            hosttoken: 'token27',
            title: '动物视频1',
            content: "萌宠日常",
            videoUrl: 'https://example.com/video27.mp4',
            coverUrl: 'https://example.com/cover27.jpg',
            loveCount: 2700,
            fensiCount: 1350,
            timer: '2024-06-27 12:00:00',
            longer: '05:00',
            alt: '动物封面1',
            commentCount: 270,
        },
        {
            id: 28,
            hostName: '动物主播2',
            hostAvatar: 'https://example.com/avatar28.jpg',
            hostId: 28,
            hosttoken: 'token28',
            title: '动物视频2',
            content: "野生动物",
            videoUrl: 'https://example.com/video28.mp4',
            coverUrl: 'https://example.com/cover28.jpg',
            loveCount: 2800,
            fensiCount: 1400,
            timer: '2024-06-28 12:00:00',
            longer: '08:00',
            alt: '动物封面2',
            commentCount: 280,
        }
    ],
    15: [
        {
            id: 29,
            hostName: '三农主播1',
            hostAvatar: 'https://example.com/avatar29.jpg',
            hostId: 29,
            hosttoken: 'token29',
            title: '三农视频1',
            content: "农村生活",
            videoUrl: 'https://example.com/video29.mp4',
            coverUrl: 'https://example.com/cover29.jpg',
            loveCount: 2900,
            fensiCount: 1450,
            timer: '2024-06-29 12:00:00',
            longer: '10:00',
            alt: '三农封面1',
            commentCount: 290,
        },
        {
            id: 30,
            hostName: '三农主播2',
            hostAvatar: 'https://example.com/avatar30.jpg',
            hostId: 30,
            hosttoken: 'token30',
            title: '三农视频2',
            content: "农业技术",
            videoUrl: 'https://example.com/video30.mp4',
            coverUrl: 'https://example.com/cover30.jpg',
            loveCount: 3000,
            fensiCount: 1500,
            timer: '2024-06-30 12:00:00',
            longer: '12:00',
            alt: '三农封面2',
            commentCount: 300,
        }
    ],
    16: [
        {
            id: 31,
            hostName: '汽车主播1',
            hostAvatar: 'https://example.com/avatar31.jpg',
            hostId: 31,
            hosttoken: 'token31',
            title: '汽车视频1',
            content: "汽车评测",
            videoUrl: 'https://example.com/video31.mp4',
            coverUrl: 'https://example.com/cover31.jpg',
            loveCount: 3100,
            fensiCount: 1550,
            timer: '2024-07-01 12:00:00',
            longer: '15:00',
            alt: '汽车封面1',
            commentCount: 310,
        },
        {
            id: 32,
            hostName: '汽车主播2',
            hostAvatar: 'https://example.com/avatar32.jpg',
            hostId: 32,
            hosttoken: 'token32',
            title: '汽车视频2',
            content: "驾驶技巧",
            videoUrl: 'https://example.com/video32.mp4',
            coverUrl: 'https://example.com/cover32.jpg',
            loveCount: 3200,
            fensiCount: 1600,
            timer: '2024-07-02 12:00:00',
            longer: '18:00',
            alt: '汽车封面2',
            commentCount: 320,
        }
    ],
    17: [
        {
            id: 33,
            hostName: '美妆主播1',
            hostAvatar: 'https://example.com/avatar33.jpg',
            hostId: 33,
            hosttoken: 'token33',
            title: '美妆视频1',
            content: "化妆教程",
            videoUrl: 'https://example.com/video33.mp4',
            coverUrl: 'https://example.com/cover33.jpg',
            loveCount: 3300,
            fensiCount: 1650,
            timer: '2024-07-03 12:00:00',
            longer: '10:00',
            alt: '美妆封面1',
            commentCount: 330,
        },
        {
            id: 34,
            hostName: '美妆主播2',
            hostAvatar: 'https://example.com/avatar34.jpg',
            hostId: 34,
            hosttoken: 'token34',
            title: '美妆视频2',
            content: "护肤分享",
            videoUrl: 'https://example.com/video34.mp4',
            coverUrl: 'https://example.com/cover34.jpg',
            loveCount: 3400,
            fensiCount: 1700,
            timer: '2024-07-04 12:00:00',
            longer: '12:00',
            alt: '美妆封面2',
            commentCount: 340,
        }
    ],
}

// 根据 tabcar 获取对应的数据
// 获取视频数据函数
export default function getVideo({ tabcar }: { tabcar: number }): Promise<VideoData[]> {
    return new Promise((resolve) => {
        // 模拟异步请求
        setTimeout(() => {
            const data = videoDataMap[tabcar] || videoDataMap[1] || [];
            resolve(data);
        }, 100);
    });
}

// 保留原有的 axios 请求方式，用于真实 API 调用
export function getVideoByAxios(url: string) {
    return axios.get(url);
}
